### ISSUE TITLE
implement windowtime

### ISSUE THREAD

**Issue by wilson-young** [menelai/http-request-cache#24]
Hi Sir,
I was trying to use the http-reuest-cache
but we need to set expiration for the certain cache
so i tried to modify the decorator
i tried to add the windowtime in shareReplay which is work
but the observerble was saved in dataStorage Map

can i know is it possible for implement windowTime in current decorator structure?

**Comment by menelai** [comment]
Hi! Thanks foк your interest. I added windowTime option to v1.1.0

**Comment by wilson-young** [comment]
Hi Sir,
let say i set windowTime i set to 10seconds

after 10 seconds
datastorage.getItem(key) is being called and store to observable

and it wont get in to if(!observable) in decorator

**Comment by wilson-young** [comment]
so after 10sec 
the data is cleared from cache
but it wont retrieve data from API
and stuck there forever until refresh browser 

do you have any advice? @menelai
